#!/usr/bin/env sh

: ${S3_ACCESS_KEY_ID}
: ${S3_BUCKET}
: ${S3_ENDPOINT}
: ${S3_REGION}
: ${S3_SECRET_ACCESS_KEY}

juicefs format \
    --access-key="$S3_ACCESS_KEY_ID" \
    --bucket="https://${S3_BUCKET}.${S3_ENDPOINT}" \
    --secret-key="$S3_SECRET_ACCESS_KEY" \
    --storage="s3" \
    sqlite3://myjfs.db \
    "$S3_BUCKET"
