#!/usr/bin/env sh

: ${ENCRYPTION_PASSWORD}
: ${S3_ACCESS_KEY_ID}
: ${S3_BUCKET}
: ${S3_ENDPOINT}
: ${S3_REGION}
: ${S3_SECRET_ACCESS_KEY}

S3_PATH=""

sed -E \
    -e "s|<access_key_id>|${S3_ACCESS_KEY_ID}|" \
    -e "s|<bucket>|${S3_BUCKET}|" \
    -e "s|<encryption_password>|${ENCRYPTION_PASSWORD}|" \
    -e "s|<endpoint>|${S3_ENDPOINT}|" \
    -e "s|<path>|${S3_PATH}|" \
    -e "s|<region>|${S3_REGION}|" \
    -e "s|<secret_access_key>|${S3_SECRET_ACCESS_KEY}|" \
    -i /etc/zerofs/config.toml
